---
name: MUHAMMAD
surname: ILYAS
#position: "Postdoctoral Research Fellow"
#address: "Department of Psychology, University of Michigan"
#www: sites.lsa.umich.edu/hanzh
email: "ilyaszarif@gmail.com, muhammadilyas@bs.qau.edu.pk"
#orcid: 0000-0001-6087-0428
#researchgate: Han_Zhang175
#github: HanZhang-psych
#twitter: \_HanZhang_
headcolor: 414141 # use black color
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
#pandoc_args: ["--lua-filter=multiple-bibliographies.lua"] # used for creating bibliographies for multiple sections
#csl: apa-cv.csl # change this if you want to use other citation styles
#bibliography_published: "Published.bib" # use separate .bib files and #assign each of them a unique key: bibliography_*
#bibliography_underreview: "Under review.bib"
#bibliography_inprep: "In prep.bib"
#bibliography_presentations: "Presentations.bib"
#nocite: '@*' # don't change this if you want to print out all the refs
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae);library(tibble)
```

# Research Interests
Conservation Genetics and Behavioral Ecology 

# Education

```{r}
tribble(
  ~ Degree,  ~ Year, ~ Institution, ~ Where,~Thesis,
  "Master of Philosophy, Zoology (Wildlife Ecology)", "09/2017-07/2020", "Quaid-i-Azam University Islamabad", "Islamabad, Pakistan", "Thesis: Abundance Estimation of Himalayan Lynx Through Multiple Modelling Approach",
  "Bachelor of Science, Zoology", "09/2013-07/2017", "Islamia College Peshawar", "Peshawar, Pakistan", NA,
) %>% 
  detailed_entries(with=Degree, what=Institution, when=Where,  where=Year, why=Thesis)
```

# Working Experience
```{r}
tribble(
   ~Position,~Year, ~Employer, ~Where,~Responsibilities,
  "Research Assistant", "09/2017-02/2020", "Carnivore Conservation Lab: Department of Zoology, Quaid-i-Azam University Islamabad","Islamabad, Pakistan", "Field Survey designing and implimentation; Research data Collection and analysis"
) %>% 
  detailed_entries(
    where = Year,
    when = Where,
    with = Position, 
    what = Employer,
    why=  Responsibilities
  )
```

# Research Grants
```{r}
tribble(
  ~Year, ~Name, ~Funding_Agency,
  2018, "Mammalian Diversity Assessment in Chitral Gol National Park ($3000)", "National Parks Project: Wildlife Department Khyber Pakhtunkhwa,
  Pakistan Snowleopard and Ecosystem Protection Program: Snowleopard Foundsation",
) %>% 
  detailed_entries(
    where = Year,
    with = Name, 
    what = Funding_Agency
  )
```




# Teaching Experience

## Primary Instructor

```{r}
tribble(
  ~Year, ~Name, ~Duty,
  '09/2017 - 12/2017', "EDUC 391: Educational Psychology and Human Development","Course design; weekly lectures; grading assignments and exams; office hours"
) %>% 
  detailed_entries(
    where = Year,
    with = Name, 
    what = Duty
  )
```


## Graduate Student Instructor

```{r}
tribble(
  ~Year, ~Name, ~Duty,
  '01/2020 - 05/2020', "PSYCH 457 : Research in Educational and Cross-Cultural Settings", "Grading student essays; office hours; supervising student research projects",
  '01/2019 - 04/2019',"PSYCH 457 : Research in Educational and Cross-Cultural Settings","Grading student essays; office hours; supervising student research projects",
  '01/2018 - 04/2018', "PSYCH 111: Introduction to Psychology","Three review sessions per week; grading assignments and exams; office hours",
  '01/2017 - 04/2017', "PSYCH 457 : Research in Educational and Cross-Cultural Settings","Grading student essays; office hours; supervising student research projects",
  '09/2016 - 12/2016', "PSYCH 240: Intro to Cognitive Psychology","Three review sessions per week; grading assignments and exams; office hours",
  '01/2016 - 04/2016', "PSYCH 457 : Research in Educational and Cross-Cultural Settings","Grading student essays; office hours; supervising student research projects"
) %>% 
  detailed_entries(
    where = Year,
    with = Name, 
    what = Duty
  )
```

## Program Assistant

```{r}
tribble(
  ~Year, ~Name, ~Duty,
  '05/2019',  "Global Course Connection: Beijing Normal University", "Supervising joint research projects between US and Chinese students; organizing student activities",
  '05/2017', 'Global Course Connection: Beijing Normal University',  "Supervising joint research projects between US and Chinese students; organizing student activities",
  '05/2016', "Global Course Connection: Beijing Normal University", "Supervising joint research projects between US and Chinese students; organizing student activities",
  '05/2015', "Global Course Connections: Beijing Normal University", "Supervising joint research projects between US and Chinese students; organizing student activities"
) %>% 
  detailed_entries(
    where = Year,
    with = Name, 
    what = Duty
  )
```

# Professional Service

## Ad Hoc Reviewer

* Journal of Experimental Psychology: General
* Memory & Cognition

# References

```{r}
tribble(
  ~Name, ~Title, ~Contact,
  'John Jonides, Ph.D.',  "Edward E. Smith Professor of Psychology and Neuroscience; Co-Director, functional MRI Center, University of Michigan; Senior Editor, Psychological Science", "jjonides@umich.edu; 734-764-0192",
  'Kevin F. Miller, Ph.D.',  "Professor of Psychology and Education,  University of Michigan", "kevinmil@umich.edu; 734-615-1800",
  'Priti Shah, Ph.D.',  "Professor of Cognition & Cognitive Neuroscience and Educational Psychology, University of Michigan", "priti@umich.edu; 734-615-3745",
  'Kai S. Cortina, Ph.D.',  "Professor of Psychology, University of Michigan", "schnabel@umich.edu; 734-615-3809"
) %>% 
  detailed_entries(
    where = Contact,
    with = Name, 
    what = Title
  )
```